local Unit_Info_Table = {

    	  ["REP_ACCLAMATOR"] = { meshes ={   "EngineGlow",
									            "Hull",
									            "Lights",
									            "Shadow" },

                                     heights = {"Height_01",
                                                "Height_02",
												"Height_03",
                                                "Height_04",
												"Height_05",
                                                "Height_06",
												"Height_07",
                                                "Height_08",
												"Height_09",
                                                "Height_10",
												"Height_11",
                                                "Height_12",
												"Height_13",
}
                                   },
		  
		  ["VENATOR_SD"] = { meshes ={      "EngineGlow04",
                                      			"Engines",
							"Hangar",
                                      			"Hangar_Door01",
							"Hangar_Door02",
                                      			"Hull",
							"Main_Hull_lights",
                                      			"Shadow" },

                                     heights = {"Height_01",
                                                "Height_02",
												"Height_03",
                                                "Height_04",
												"Height_05",
                                                "Height_06",
												"Height_07",
                                                "Height_08",
												"Height_09",
                                                "Height_10",
												"Height_11",
                                                "Height_12",
												"Height_13"}
                                   },
                                   
          ["MUNIFICENT_FRIGATE"] = { meshes ={  "EngineGlow",
							"Hull",
							"Lights" },

                                     heights = {"Height_01",
                                                "Height_02",
												"Height_03",
                                                "Height_04",
												"Height_05",
                                                "Height_06",
												"Height_07",
                                                "Height_08",
												"Height_09",
                                                "Height_10",
												"Height_11",
                                                "Height_12",
												"Height_13"}
                                   },
                                   
        ["BULWARK_MKI"] = { meshes ={ 	"EngineGlow",
                                      			"HangarLights",
							"HangarShield",
                                      			"Hull",
							"Lights",
                                      			"Shadow" },

                                     heights = {"Height_01",
                                                "Height_02",
												"Height_03",
                                                "Height_04",
												"Height_05",
                                                "Height_06",
												"Height_07",
                                                "Height_08",
												"Height_09",
                                                "Height_10",
												"Height_11",
                                                "Height_12",
												"Height_13"}
                                   },
                                   
          ["RECUSANT_FRIGATE"] = { meshes ={   "Details",
                                      			"EngineGlow",
									 			"Hull",
                                      			"Lights" },

                                     heights = {"Height_01",
                                                "Height_02",
												"Height_03",
                                                "Height_04",
												"Height_05",
                                                "Height_06",
												"Height_07",
                                                "Height_08",
												"Height_09",
                                                "Height_10",
												"Height_11",
                                                "Height_12",
												"Height_13"}
                                   },
                                   
                                   
         ["LUCREHULK"] = { meshes ={ 	"EngineGlow",
                                      			"Engines",
							"HangarLights",
                                      			"HangarShields",
							"Lights",
                                      			"RegCoreship",
							"RegRingDetails",
                                      			"Rings"  },

                                     heights = {"Height_01",
                                                "Height_02",
												"Height_03",
                                                "Height_04",
												"Height_05",
                                                "Height_06",
												"Height_07",
                                                "Height_08",
												"Height_09",
                                                "Height_10",
												"Height_11",
                                                "Height_12",
												"Height_13"}
                                   },
                                   
          ["CAPTOR_CARRIER"] = { meshes ={ "Engine_Glow",
                                    			 "Hangar",
												 "hangar_shield",
												 "Hull",
												 "Lights"},

                                     heights = {"Height_01",
                                                "Height_02",
												"Height_03",
                                                "Height_04",
												"Height_05",
                                                "Height_06",
												"Height_07",
                                                "Height_08",
												"Height_09",
                                                "Height_10",
												"Height_11",
                                                "Height_12",
												"Height_13"}
                                   },
                                   
["VICTORY_SD"] = { meshes ={ 				"EngineGlow",
                                    			 "HangarLight",
												 "HangarShields",
												 "Hull",
												 "HullShadow",
												 "Lights",
												 "Superstructure",
												 "SuperstructureShadow" },

                                     heights = {"Height_01",
                                                "Height_02",
												"Height_03",
                                                "Height_04",
												"Height_05",
                                                "Height_06",
												"Height_07",
                                                "Height_08",
												"Height_09",
                                                "Height_10",
												"Height_11",
                                                "Height_12",
												"Height_13"}
                                   },
                                   
                                   
            ["CARRACK_LIGHT_CRUISER"] = { meshes ={ 		"EngineGlow",
                                   			    "Hull",
											    "Hull_Shadow" },

                                     heights = {"Height_01",
                                                "Height_02",
												"Height_03",
                                                "Height_04",
												"Height_05",
                                                "Height_06",
												"Height_07",
                                                "Height_08",
												"Height_09",
                                                "Height_10",
												"Height_11",
                                                "Height_12",
												"Height_13"}
                                   },
                                   
                                   
          ["ROTHANA_BATTLECRUISER"] = { meshes ={"EngineGlow",
                                      			"HangarGlow",
                                      			"Hull",
							"HullShadow",
                                      			"Lights",
							"Superstructure",
                                      			"SuperstructureShadow" },

                                     heights = {"Height_01",
                                                "Height_02",
												"Height_03",
                                                "Height_04",
												"Height_05",
                                                "Height_06",
												"Height_07",
                                                "Height_08",
												"Height_09",
                                                "Height_10",
												"Height_11",
                                                "Height_12",
												"Height_13"}
                                   },
                                   
                                   
                                   
  ["CIS_PROVIDENCE_IKM"] = { meshes ={ 				"EngineGlow",
                                   			    "HangarGlow",
                                   			    "Hull",
										        "HullShadow" },

                                     heights = {"Height_01",
                                                "Height_02",
												"Height_03",
                                                "Height_04",
												"Height_05",
                                                "Height_06",
												"Height_07",
                                                "Height_08",
												"Height_09",
                                                "Height_10",
												"Height_11",
                                                "Height_12",
												"Height_13"}
                                   },
                                   
                                   
  ["WAVECREST_FRIGATE"] = { meshes ={ 	"EngineGlow",
                                   			    "HangarLights",
										        "HangarShields",
                                   			    "Hull",
										        "Lights",
										        "RearLights",
											    "Shadow" },

                                     heights = {"Height_01",
                                                "Height_02",
												"Height_03",
                                                "Height_04",
												"Height_05",
                                                "Height_06",
												"Height_07",
                                                "Height_08",
												"Height_09",
                                                "Height_10",
												"Height_11",
                                                "Height_12",
												"Height_13"}
                                   },
                                   
 ["MANDALORIAN_KANDOSII"] = { meshes ={ 	"Engine_Glow",
                                   			    "HangarShields",
										        "Hangar_Lights",
                                   			    "Hull",
										        "Hull_Shadow",
										        "Rear",
											    "RearShadow",
											    "Window_Lights" },

                                     heights = {"Height_01",
                                                "Height_02",
												"Height_03",
                                                "Height_04",
												"Height_05",
                                                "Height_06",
												"Height_07",
                                                "Height_08",
												"Height_09",
                                                "Height_10",
												"Height_11",
                                                "Height_12",
												"Height_13"}
                                   },
                                   
                                   
                                   
  ["VICTORY_DESTROYER"] = { meshes ={ 			"Engine_Glow",
                                   			    "Hull",
										        "Lights",
										        "Lights2",
                                   			    "Turret_Base",
										        "Turret_Base_Shadow",
											    "Shadow" },

                                     heights = {"Layer_225",
                                                "Layer_175",
												"Layer_125",
                                                "Layer_75",
												"Layer_50",
                                                "Layer_25",
												"Layer_-75",
                                                "Layer_-100",
												"Layer_-150",
                                                "Layer_-200"}
                                   },
                                   
   ["ACCLAMATOR_ASSAULT_SHIP"] = { meshes ={ 	"Engine_Glow",
                                   			    "Star_Destroyer",
										        "Lights",
										        "Lights02",
										        "Bottom",
                                   			    "Shadow01",
										        "Shadow02",
										        "Shadow03" },

                                     heights = {"Layer_225",
                                                "Layer_200",
												"Layer_175",
                                                "Layer_100",
												"Layer_25",
                                                "Layer_-25",
												"Layer_-75",
                                                "Layer_-100",
												"Layer_-175",
                                                "Layer_-200"}
                                   },
                                   
                                   
   	["INTERDICTOR_CRUISER"] = { meshes ={      "Engine_Glow",
                                      			"Engines",
									  			"Engines01",
                                      			"Armor",
									  			"Armor01",
                                      			"Dominator Lights",
									  			"Dominator Parts",
                                      			"Dominator Parts01",
									  			"Gravity_Wells",
									  			"Gravity_Wells01",
                                      			"Hanger",
									  			"Hanger_Lights",
                                      			"Hull",
									  			"Hull03",
									  			"Hull02",
                                      			"Hull01",
									  			"Ion_Quad_Base",
									  			"Ion_Quad_Base01",
									  			"ISD details",
                                      			"ISD details 03",
									  			"ISD details 2",
									  			"ISD details01",
									  			"Lights" },

                                     heights = {"Layer_0",
                                                "Layer_-50",
												"Layer_-125",
                                                "Layer_-150",
												"Layer_-175",
                                                "Layer_-200",
												"Layer_-225",
                                                "Layer_-250",
												"Layer_-275",
                                                "Layer_-300"}
                                   },
                                   
                                   
                                   
        ["IMPERIAL_ESCORT_CARRIER"] = { meshes ={ "Hanger_Lights",
                                    			 "Hull",
												 "Shadow",
												 "WIndows"},

                                     heights = {"Layer_125",
                                                "Layer_75",
												"Layer_50",
                                                "Layer_-25",
												"Layer_-50",
                                                "Layer_-75",
												"Layer_-100",
                                                "Layer_-150",
												"Layer_-175",
                                                "Layer_-250"}
                                   },
                                   
      ["PROCURSATOR"] = { meshes ={   "Engine Glow",
                                    			 "Flaps",
												 "Flaps_Shadow",
												 "Hull",
												 "Hull_Shadow",
												 "Lights",
												 "Super Structure",
												 "Super Structure Shadow"},

                                     heights = {"Layer_-25",
                                                "Layer_-50",
												"Layer_-75",
                                                "Layer_-125",
												"Layer_-150",
                                                "Layer_-175",
												"Layer_-200",
                                                "Layer_-250",
												"Layer_-275",
                                                "Layer_-300"}
                                   },
                                   
     ["MC30_FRIGATE"] = { meshes ={ 			"Engine_Glow",
                                   			    "Hull",
										        "Lights",
											    "Shadow" },

                                     heights = {"Layer_125",
                                                "Layer_75",
												"Layer_50",
                                                "Layer_-25",
												"Layer_-50",
                                                "Layer_-75",
												"Layer_-100",
                                                "Layer_-150",
												"Layer_-175",
                                                "Layer_-250"}
                                   },
                                   
                                   
      ["CRUSADER_GUNSHIP"] = { meshes ={		"Engine_Glow",
                                   			    "Hull",
										        "Lights",
											    "Shadow" },

                                     heights = {"Layer_175",
                                                "Layer_150",
												"Layer_125",
                                                "Layer_75",
												"Layer_50",
                                                "Layer_0",
												"Layer_-50",
                                                "Layer_-75",
												"Layer_-125",
                                                "Layer_-150"}
                                   },
                                   
                                   
                                   
         ["INTERCEPTOR4_FRIGATE"] = { meshes ={ "Engine_Glow",
                                      			"Hanger",
									  			"Heavy_Ion_Cannons",
									  			"Heavy_Ion_Cannons_Shadow",
									  			"Hull",
									  			"Lights",
									  			"Shadow"  },

                                     heights = {"Layer_175",
                                                "Layer_150",
												"Layer_100",
                                                "Layer_75",
												"Layer_25",
                                                "Layer_0",
												"Layer_-25",
                                                "Layer_-50",
												"Layer_-100",
                                                "Layer_-150"}
                                   },
                                   
       ["KRAYT_CLASS_DESTROYER"] = { meshes ={ "Engine_Glow",
                                      			"Hanger",
									  			"Heavy_Ion_Cannons",
									  			"Heavy_Ion_Cannons_Shadow",
									  			"Hull",
									  			"Lights",
									  			"Shadow"  },

                                     heights = {"Layer_125",
                                                "Layer_75",
												"Layer_50",
                                                "Layer_25",
												"Layer_0",
                                                "Layer_-50",
												"Layer_-75",
                                                "Layer_-150",
												"Layer_-175",
                                                "Layer_-250"}
                                   },
                                   
        ["VALIANT"] = { meshes ={ 				"Engine_Glow",
                                      			"Engines",
									  			"Hanger_Lights",
									  			"Hanger_Normal",
									  			"Hull",
									  			"Hull_Small",
									  			"Lights",
									  			"Shadow"  },

                                     heights = {"Layer_50",
                                                "Layer_0",
												"Layer_-25",
                                                "Layer_-75",
												"Layer_-100",
                                                "Layer_-125",
												"Layer_-150",
                                                "Layer_-200",
												"Layer_-225",
                                                "Layer_-250"}
                                   },
                                   
      ["VENGEANCE_FRIGATE"] = { meshes ={		"Engine_Glow",
                                      			"Gun_01",
									  			"Gun_02",
									  			"Gun_03",
									  			"Gun_04",
                                      			"Gun_Shadow_01",
									  			"Gun_Shadow_02",
									  			"Gun_Shadow_03",
									  			"Gun_Shadow_04",
									  			"Hull",
									  			"Lights",
									  			"Lights02",
									  			"Shadow"  },

                                     heights = {"Layer_125",
                                                "Layer_75",
												"Layer_50",
                                                "Layer_-25",
												"Layer_-50",
                                                "Layer_-75",
												"Layer_-100",
                                                "Layer_-150",
												"Layer_-175",
                                                "Layer_-250"}
                                   },
                                   
        ["KEDALBE_BATTLESHIP"] = { meshes ={  	 "Box01",
                                    			 "FireLights",
												 "FirePortDown",
												 "FirePortDown_Shadow",
                                    			 "FirePortDownEyes",
												 "FirePortUp",
												 "FirePortUp_Shadow",
                                    			 "FirePortUpEyes",
												 "Hadron_Charge",
												 "Hull",
                                    			 "Hull_Shadow",
												 "Lights",
												 "Wings",
												 "Wings_Shadow"},

                                     heights = {"Layer_75",
                                                "Layer_25",
												"Layer_-0",
                                                "Layer_-75",
												"Layer_-125",
                                                "Layer_-150",
												"Layer_-200",
                                                "Layer_-225",
												"Layer_-275",
                                                "Layer_-300"}
                                   },
                                   

        ["KANDO12"] = { meshes ={ 				"Engine_Glow",
                                      			"Exhaust",
									  			"Hanger_Lights",
									  			"Hanger",
									  			"Hull",
									  			"Rear",
									  			"Window_Lights",
									  			"Shadow"  },

                                     heights = {"Layer_0",
                                                "Layer_50",
												"Layer_125",
                                                "Layer_150",
												"Layer_175",
                                                "Layer_200",
												"Layer_225",
                                                "Layer_250",
												"Layer_275",
                                                "Layer_300"}
                                   },
                                   
                                   
      ["JEDI_CRUISER_E"] = { meshes ={  		 "Engine_Glow",
                                    			 "Hanger",
												 "Hanger_Lights",
												 "Hull",
                                    			 "Ion_Emitor",
												 "Lights",
												 "Lights02",
                                    			 "Object02",
												 "Shadow"},

                                     heights = {"Layer_0",
                                                "Layer_25",
												"Layer_50",
                                                "Layer_75",
												"Layer_100",
                                                "Layer_125",
												"Layer_150",
                                                "Layer_175",
												"Layer_200",
                                                "Layer_225"}
                                   },
                                   
      ["JEDI_CRUISER_R"] = { meshes ={  		 "Engine_Glow",
                                    			 "Hanger",
												 "Hanger_Lights",
												 "Hull",
                                    			 "Ion_Emitor",
												 "Lights",
												 "Lights02",
                                    			 "Object02",
												 "Shadow"},

                                     heights = {"Layer_0",
                                                "Layer_25",
												"Layer_50",
                                                "Layer_75",
												"Layer_100",
                                                "Layer_125",
												"Layer_150",
                                                "Layer_175",
												"Layer_200",
                                                "Layer_225"}
                                   },
                                   
      ["JEDI_CRUISER_P"] = { meshes ={  		 "Engine_Glow",
                                    			 "Hanger",
												 "Hanger_Lights",
												 "Hull",
                                    			 "Ion_Emitor",
												 "Lights",
												 "Lights02",
                                    			 "Object02",
												 "Shadow"},

                                     heights = {"Layer_0",
                                                "Layer_25",
												"Layer_50",
                                                "Layer_75",
												"Layer_100",
                                                "Layer_125",
												"Layer_150",
                                                "Layer_175",
												"Layer_200",
                                                "Layer_225"}
                                   },
                                   
      ["JEDI_CRUISER_U"] = { meshes ={  		 "Engine_Glow",
                                    			 "Hanger",
												 "Hanger_Lights",
												 "Hull",
                                    			 "Ion_Emitor",
												 "Lights",
												 "Lights02",
                                    			 "Object02",
												 "Shadow"},

                                     heights = {"Layer_0",
                                                "Layer_25",
												"Layer_50",
                                                "Layer_75",
												"Layer_100",
                                                "Layer_125",
												"Layer_150",
                                                "Layer_175",
												"Layer_200",
                                                "Layer_225"}
                                   }
  }

return Unit_Info_Table